### ISSUE TITLE
customize fringe symbol

### ISSUE THREAD

**Issue by adl** [AdamNiederer/cov#11]
Hi Adam,

Thank you for this neat package.  Would it be possible to make the fringe customizable?  The "empty-line" symbol is too thin for me, I have found that using "filled-rectangle" is more readable.  However redefining the `cov--get-fringe` function just to get this behavior does not seems very clean.

**Comment by AdamNiederer** [comment]
Done!
Customize `cov-fringe-symbol` to use another bitmap in the fringe once MELPA builds my last commit.
