### ISSUE TITLE
lcov parsing

### ISSUE THREAD

**Issue by xenodium** [AdamNiederer/cov#32]
First of, this package looks wonderful. Thanks for building it.

Apologies if I missed something here, but was unable to set this up using an lcov file.

I looked at the included parsers and tried explicitly parsing with

```
(cov--read-and-parse "coverage.lcov" 'gcov)
(cov--read-and-parse "coverage.lcov" 'clover)
(cov--read-and-parse "coverage.lcov" 'coveralls)
(cov--read-and-parse "coverage.lcov" 'coveragepy)
```

gcov files had no issues parsing with `(cov--read-and-parse "coverage.gcov" 'gcov)`.

The coverage.lcov file had the following content:

```
SF:/private/tmp/Foo/Sources/Foo/Foo.swift
FN:4,$s3FooAAV5greet15defaultGreetingySb_tF
FNDA:1,$s3FooAAV5greet15defaultGreetingySb_tF
FNF:1
FNH:1
DA:4,1
DA:5,1
DA:6,1
DA:7,1
DA:8,0
DA:9,1
DA:10,1
LF:7
LH:6
end_of_record
```

> Currently, it supports gcov, lcov, and clover output, as well as the Coveralls format produced by undercover.el.

README mentioned lcov support, so I'm wondering if conversion is needed? Should I have tried something else?

Thank you.

**Comment by dhanak** [comment]
I was wondering the same... Help would be appreciated.

**Comment by Aaronzinhoo** [comment]
@xenodium @dhanak , going through the source code it seems to only support `gcov`. I think there should be a combination of this package and [coverlay](https://github.com/twada/coverlay.el/issues)

**Comment by snogge** [comment]
cov.el does not support the .info files that lcov uses. They are actually a gcov intermediate format that should be supported. I was planning to add that but got stuck with #23 - which I have still not fixed.  
Adding a parser for .info should not be complicated.  Patches are welcome. @AdamNiederer is not active in the issues but in my experience he does review and merge PRs quickly.

**Comment by snogge** [comment]
I've implemented a lcov parser, but I'm still working in the lookup functions.  Any ideas on how you should go from a source file to a lcov info file would be appreciated.
